### ISSUE TITLE
Choosing suitable attribute fields with URLs and images in Myplaceimport

### ISSUE THREAD

**Issue by SannaJokela** [oskariorg/oskari-server#169]
When adding own datasets through Myplaceimport, it would be convenient if one could choose if some of the attributes has image links or plain URLs. This could be either done by automated detection of URL and links ending with image format (.jpg, .png) or user could choose which attributes are links / images. Also if this would be the case, users could also choose the attributes they want to be shown in pop-up infobox.

**Comment by ZakarFin** [comment]
Issues for Oskari should be reported under oskari-docs as this issues section will be closed (hopefully) in the near future. The same ticket was reported there oskariorg/oskari-docs#65 so closing this as duplicate.
