### ISSUE TITLE
transport not working with Jetty 9

### ISSUE THREAD

**Issue by iluwatar** [oskariorg/oskari-server#20]
http://oskari.org/documentation/backend/installing-transport

With Jetty 9, the instructions do not work. The websocket connection cannot be established. I had added the websockets module to Jetty with `--module=websocket.`

After I downgraded to Jetty 8, everything works out of the box.

**Comment by ZakarFin** [comment]
Seems that Cometd 2.x which we use for websocket communication doesn't support Jetty 9. We will update the installation document and at least consider updating the Cometd version in the near future.

**Comment by hatapitk** [comment]
I did some initial work on using Cometd 3. I will not make a real pull request as I believe this is not enough or necessarily correct, but it helped us to have the user layers feature work without user visible error messages. It should at least fix the things mentioned in Cometd migration document at https://github.com/cometd/cometd-documentation/blob/master/src/main/asciidoc/migration.adoc

Things that at least still need work for Tomcat users: getting rid of org.eclipse.jetty.servlets.CrossOriginFilter and org.eclipse.jetty.servlet.* context params.

**Comment by ZakarFin** [comment]
Nice, thanks!

**Comment by ZakarFin** [comment]
Finally we are closing in on the upgrade:
- oskari-server now has a jetty-9 branch that has the modified code to make CometD work and updated GeoTools
- A downloadable Jetty 9 package with Oskari 1.48.0 + the above changes is available at http://oskari.org/build/server/jetty-9.4.12-oskari.zip for testing

**Comment by ZakarFin** [comment]
Fixed in jetty-9 branch that will be released as 1.50.0
