### ISSUE TITLE
User layers not deleted, when user account is deleted.

### ISSUE THREAD

**Issue by an9l** [oskariorg/oskari-server#30]
When admin deletes the user account, the corresponding user layers data, which are added by that user, are not deleted from database. 
https://github.com/nls-oskari/oskari-server/blob/master/control-admin/src/main/java/fi/nls/oskari/control/admin/UsersHandler.java

And also same might be the case with analysis and myplace data, but not tested.

**Comment by ZakarFin** [comment]
I think this is a bit larger issue. We should have some mechanic for figuring out services that handle user-generated content. That way we don't need to hardcode references to these services on the user handling.

**Comment by ZakarFin** [comment]
Fixed in version 1.42.1
