### ISSUE TITLE
Wishlist: filtering option for metadata catalogue

### ISSUE THREAD

**Issue by hatapitk** [oskariorg/oskari-server#37]
It would be useful if metadata search functionality could be limited to display only layers that are registered in the current Oskari instance. Example: metadata for all layers available in Biomass atlas is stored Paikkatietohakemisto but we cannot use the search functionality because the returned results will contain many records that refer to layers that are not available in Biomass atlas and thus confuse the user.

The filtering option could be implemented by comparing metadata IDs. Alternatively there could be a way to force some other filter condition that would not be shown in the user interface.

**Comment by ZakarFin** [comment]
This will be included in the 1.41 release that's scheduled for 22.2.2017. Can you test if it solves the issue for you?
